/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.clowngraphics.rerenderer;

import io.github.clowngraphics.rerenderer.model.Model;
import io.github.clowngraphics.rerenderer.model.transform.ModelTransform;
import io.github.clowngraphics.rerenderer.window.GraphicUserInterface;
import javafx.scene.canvas.GraphicsContext;

public class App {
    public static void main(String[] args) {
        RenderTest.main(null);
    }
}
