/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.clowngraphics.rerenderer;

import io.github.clowngraphics.rerenderer.model.Model;
import io.github.clowngraphics.rerenderer.model.transform.ModelTransform;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        RenderTestFrame.main(null);
    }
}
