/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.ClownGrapics.Rerenderer;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.stage.Stage;
import javafx.stage.Window;

import java.io.IOException;

public class App {

    public static void main(String[] args) {
        WindowApp.main(null);
    }

}
